# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '61dbae51-cdd9-4380-ba89-78dd6c20b4d7'

steps:
- task: DotNetCoreCLI@2
  displayName: Build Function App
  inputs:
    command: build
# - task: AzureFunctionApp@1
#   inputs:
#     azureSubscription: '$(azureSubscription)'
#     appName: 'samplefunctionapp'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'